{{- range .Values.ldapSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ include "userGroupOperator.namespaceName" $ }}
  labels:
    {{- include "userGroupOperator.labels" $ | nindent 4 }}
data:
  bindDn: {{ .bindDn | b64enc }}
  bindPassword: {{ .bindPassword | b64enc }}
{{- end }}
