{{- range .Values.ldapSecrets }}
{{- if .bitwardenSecretName }}
---
apiVersion: bitwarden-k8s-secrets-manager.demo.redhat.com/v1
kind: BitwardenSyncSecret
metadata:
  name: {{ .name }}
  namespace: {{ include "userGroupOperator.namespaceName" $ }}
spec:
  data:
    bindDn:
      secret: {{ .bitwardenSecretName }}
      key: bindDn
    bindDn:
      secret: {{ .bitwardenSecretName }}
      key: bindPassword
{{- else }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ include "userGroupOperator.namespaceName" $ }}
  labels:
    {{- include "userGroupOperator.labels" $ | nindent 4 }}
data:
  bindDn: {{ .bindDn | b64enc }}
  bindPassword: {{ .bindPassword | b64enc }}
{{- end }}
{{- end }}
