{{- range .Values.salesforceSecrets }}
{{- if .bitwardenSecretName }}
---
apiVersion: bitwarden-k8s-secrets-manager.demo.redhat.com/v1
kind: BitwardenSyncSecret
metadata:
  name: {{ .name }}
  namespace: {{ include "userGroupOperator.namespaceName" $ }}
spec:
  data:
    tls.key:
      secret: {{ .bitwardenSecretName }}
      {{- if .bitwardenSecretKey }}
      key: {{ .bitwardenSecretKey }}
      {{- end }}
{{- else }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ include "userGroupOperator.namespaceName" $ }}
  labels:
    {{- include "userGroupOperator.labels" $ | nindent 4 }}
data:
  tls.key: {{ .consumerSecret | b64enc }}
{{- end }}
{{- end }}
