{{- range .Values.salesforceSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ include "userGroupOperator.namespaceName" $ }}
  labels:
    {{- include "userGroupOperator.labels" $ | nindent 4 }}
data:
  tls.key: {{ .consumerSecret | b64enc }}
{{- end }}
