apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: usergroupconfigs.usergroup.gpte.redhat.com
spec:
  group: usergroup.gpte.redhat.com
  scope: Cluster
  names:
    plural: usergroupconfigs
    singular: usergroupconfig
    kind: UserGroupConfig
    shortNames: []
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        description: >-
          Configuration for user-group-operator.
        type: object
        required:
        - apiVersion
        - kind
        - metadata
        - spec
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
            properties:
              name:
                type: string
          spec:
            description: >-
              User Group Operator configuration.
            type: object
            properties:
              emailDomainGroups:
                type: object
                properties:
                  enable:
                    default: false
                    type: boolean
                  prefix:
                    type: string
                    default: email-domain.
              identityProviderGroups:
                type: object
                properties:
                  enable:
                    default: false
                    type: boolean
                  prefix:
                    type: string
                    default: identity-provider.
